apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: m-ecommerce
  labels:
    app: payment-service
spec:
  selector:
    app: payment-deployment
  ports:
    - protocol: TCP
      port: 5003
      targetPort: 5003